language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sagarbhp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sagarbhp/docker-react npm run test