language: ruby

services:
  - docker

before_install:
  - docker build -t sagarbhp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sagarbhp/docker-react npm run test

deploy:
  provider: elasticbeanstack
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-441046298192"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY